name: repo20250614-main
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen"
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show current directory
        run: pwd

      - name: List files in current directory
        run: ls -al

